name: Running Build And Test

on:
  workflow_call:
    inputs:
      project:
        required: true
        type:     string
      runid:
        required: true
        type:     string
      region:
        required: true
        type:     string
    secrets:
      username:
        required: true
      token:
        required: true
      keyid:
        required: true
      key:
        required: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.project }}-artifacts-${{ inputs.runid }}
          path: ${{ inputs.project }}
      - uses: actions/download-artifact@v3
        with:
          name: golang-common-artifacts-${{ inputs.runid }}
          path: golang-common
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6' # The Go version to download (if necessary) and use.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.keyid }}
          aws-secret-access-key: ${{ secrets.key }}
          aws-region: ${{ inputs.region }}
      - name: Build, tag, and push image to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.keyid }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.key }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        working-directory: ${{ inputs.project }}
        run:  make build
      - name: run unit testing
        working-directory: ${{ inputs.project }}
        run: |
          make test
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.project }}-artifacts-${{ github.run_id }}
          path: ${{ inputs.project }}
