name: Reusable Code Checkout With Golang-common and Submodule

on:
  workflow_call:
    inputs:
      project:
        required: true
        type:     string
      runid:
        required: true
        type:     string
    secrets:
      username:
        required: true
      token:
        required: true
      sshkey:
        required: true
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.token }}
          path: ${{ inputs.project }}
      - name: Extract dest branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF#refs/heads/})"
        id: extract_dest_branch
      - name: check out golang-common library
        if: inputs.project != 'golang-common'
        uses: actions/checkout@v3
        with:
          repository : appaegis/golang-common
          ref        : ${{ steps.extract_dest_branch.outputs.branch }}
          path       : golang-common
          ssh-key : ${{ secrets.sshkey }}
          fetch-depth: 0
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.project }}-artifacts-${{ inputs.runid }}
          path: ${{ inputs.project }}
      - uses: actions/upload-artifact@v2
        if: ${{ inputs.project }} != golang-common
        with:
          name: golang-common-artifacts-${{ inputs.runid }}
          path: golang-common
