name: Reusable Code Coverage Status For A Commit

on:
  workflow_call:
    inputs:
      organization:
        required: true
        type:     string
      project:
        required: true
        type:     string
      commit:
        required: true
        type:     string
      runid:
        required: true
        type:     string
      pullreq:
        required: true
        type:     string
    secrets:
      username:
        required: true
      token:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Coverage Status Update
        run:|
          curl "https://{GIT_USER}:${GIT_TOKEN}@api.github.com/repos/${ORG_NAME}/${PROJECT_NAME}/statuses/${COMMIT_SHA}" -d "{\"state\": \"pending\",\"target_url\": \"https://github.com/${ORG_NAME}/${PROJECT_NAME}/pull/${PULL_NUMBER}/checks?check_run_id=${RUN_ID}\",\"description\": \"in progress — This check has started... \",\"context\": \"code cov\"}"
        with:
          GIT_TOKEN: ${{ secrets.token }}
          GIT_USER:  ${{ secrets.username }}
          ORG_NAME:  ${{ inputs.organization }}
          PROJECT_NAME: ${{ inputs.project }}
          COMMIT_SHA:   ${{ inputs.commit }}
          RUN_ID:       ${{ inputs.runid }}
          PULL_NUMBER:  ${{ inputs.pullreq }}
